import turtle as t 
scale = int(input("ENTER THE SCALE: "))
lof1bar = int(input("ENTER DATA FOR 1ST BAR : "))
lof2bar = int(input("ENTER DATA FOR 2ND BAR : "))
lof3bar = int(input("ENTER DATA FOR 3RD BAR : "))
lof4bar = int(input("ENTER DATA FOR 4TH BAR : "))
lof5bar = int(input("ENTER DATA FOR 5TH BAR : "))
lof6bar = int(input("ENTER DATA FOR 6TH BAR : "))
lof7bar = int(input("ENTER DATA FOR 7TH BAR : "))
lof8bar = int(input("ENTER DATA FOR 8TH BAR : "))
lof9bar = int(input("ENTER DATA FOR 9TH BAR : "))
lof10bar = int(input("ENTER DATA FOR 10TH BAR : "))
lof11bar = int(input("ENTER DATA FOR 11TH BAR : "))
lof12bar = int(input("ENTER DATA FOR 12TH BAR : "))
lof13bar = int(input("ENTER DATA FOR 13TH BAR : "))
lof14bar = int(input("ENTER DATA FOR 14TH BAR : "))
lof15bar = int(input("ENTER DATA FOR 15TH BAR : "))


c = scale
cc = scale * 2

title = input("ENTER THE TITLE : ")
color = input("SELECT THEME LIGHT OR DARK : ")
if color == ("Light"):
    ac = "white"
    scale_coloring = ("black")
else:
    ac = "black"   
    scale_coloring = ("white") 

wn = t.Screen()
wn.title(title)
wn.bgcolor(ac)
wn.setup(width=800, height=600)
wn.tracer(0)

# Scale heading
pen = t.Turtle()
pen.speed(0)
pen.color("red")
pen.penup()
pen.hideturtle()
pen.goto(0, 260)
pen.write("SCALE: {}".format(scale), align= "center", font=("Courier", 24, "normal"))
pen.goto(250, 260)
pen.write("=", align= "center", font=("Courier", 24, "normal"))
pen.goto(320, 260)
pen.write("Scale", align= "center", font=("Courier", 24, "normal"))

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(200, 280)
  
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 0)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -20)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 20)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -40)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 40)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -60)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 60)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -80)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 80)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -100)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 100)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -120)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 120)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -140)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 140)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -160)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 160)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -180)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 180)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -200)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 200)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -220)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 220)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -240)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 240)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -260)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 260)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -280)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 280)
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, 300)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=1, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-380, -300)

# above was stupid scale but this is good boiii Siuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -30)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 10)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -50)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 30)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -70)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 50)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -90)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 70)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -110)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 90)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -130)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 110)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -150)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 130)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -170)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 150)


paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -190)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 170)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -210)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 190)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -230)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 210)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -250)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 230)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -270)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 250)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, -290)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 290)

paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color(scale_coloring)
paddle_a.shapesize(stretch_wid=0.3, stretch_len=3)
paddle_a.penup()
paddle_a.goto(-380, 270)

# Paddle A
paddle_a = t.Turtle()
paddle_a.speed(0)
paddle_a.shape("square")
paddle_a.color("red")
paddle_a.shapesize(stretch_wid=lof1bar / scale, stretch_len=1)
paddle_a.penup()
paddle_a.goto(-350, -10)

# Paddle B
paddle_b = t.Turtle()
paddle_b.speed(0)
paddle_b.shape("square")
paddle_b.color("green")
paddle_b.shapesize(stretch_wid=lof2bar / scale, stretch_len=1)
paddle_b.penup()
paddle_b.goto(-300, -10)

# Paddle C
paddle_c = t.Turtle()
paddle_c.speed(0)
paddle_c.shape("square")
paddle_c.color("yellow")
paddle_c.shapesize(stretch_wid=lof3bar / scale, stretch_len=1)
paddle_c.penup()
paddle_c.goto(-250,-10)

# Paddle D
paddle_d = t.Turtle()
paddle_d.speed(0)
paddle_d.shape("square")
paddle_d.color("blue")
paddle_d.shapesize(stretch_wid=lof4bar / scale, stretch_len=1)
paddle_d.penup()
paddle_d.goto(-200,-10)

# Paddle E
paddle_e = t.Turtle()
paddle_e.speed(0)
paddle_e.shape("square")
paddle_e.color("purple")
paddle_e.shapesize(stretch_wid=lof5bar / scale, stretch_len=1)
paddle_e.penup()
paddle_e.goto(-150,-10)

# Paddle F
paddle_f = t.Turtle()
paddle_f.speed(0)
paddle_f.shape("square")
paddle_f.color("red")
paddle_f.shapesize(stretch_wid=lof6bar / scale, stretch_len=1)
paddle_f.penup()
paddle_f.goto(-100,-10)

# Paddle g
paddle_g = t.Turtle()
paddle_g.speed(0)
paddle_g.shape("square")
paddle_g.color("green")
paddle_g.shapesize(stretch_wid=lof7bar / scale, stretch_len=1)
paddle_g.penup()
paddle_g.goto(-50,-10)

# Paddle H
paddle_h = t.Turtle()
paddle_h.speed(0)
paddle_h.shape("square")
paddle_h.color("yellow")
paddle_h.shapesize(stretch_wid=lof8bar / scale, stretch_len=1)
paddle_h.penup()
paddle_h.goto(0,-10)

# Paddle I
paddle_i = t.Turtle()
paddle_i.speed(0)
paddle_i.shape("square")
paddle_i.color("blue")
paddle_i.shapesize(stretch_wid=lof9bar / scale, stretch_len=1)
paddle_i.penup()
paddle_i.goto(50,-10)

# Paddle j
paddle_j = t.Turtle()
paddle_j.speed(0)
paddle_j.shape("square")
paddle_j.color("purple")
paddle_j.shapesize(stretch_wid=lof10bar / scale, stretch_len=1)
paddle_j.penup()
paddle_j.goto(100,-10)


# Paddle j
paddle_j = t.Turtle()
paddle_j.speed(0)
paddle_j.shape("square")
paddle_j.color("red")
paddle_j.shapesize(stretch_wid=lof11bar / scale, stretch_len=1)
paddle_j.penup()
paddle_j.goto(150,-10)

# Paddle j
paddle_j = t.Turtle()
paddle_j.speed(0)
paddle_j.shape("square")
paddle_j.color("green")
paddle_j.shapesize(stretch_wid=lof12bar / scale, stretch_len=1)
paddle_j.penup()
paddle_j.goto(200,-10)

# Paddle j
paddle_j = t.Turtle()
paddle_j.speed(0)
paddle_j.shape("square")
paddle_j.color("yellow")
paddle_j.shapesize(stretch_wid=lof13bar / scale, stretch_len=1)
paddle_j.penup()
paddle_j.goto(250,-10)

# Paddle j
paddle_j = t.Turtle()
paddle_j.speed(0)
paddle_j.shape("square")
paddle_j.color("blue")
paddle_j.shapesize(stretch_wid=lof14bar / scale, stretch_len=1)
paddle_j.penup()
paddle_j.goto(300,-10)

# Paddle j
paddle_j = t.Turtle()
paddle_j.speed(0)
paddle_j.shape("square")
paddle_j.color("purple")
paddle_j.shapesize(stretch_wid=lof15bar / scale, stretch_len=1)
paddle_j.penup()
paddle_j.goto(350,-10)

while  True:
    wn.update()
    if 1 == 1:
        pass
else:
    pass 
